import type { CentreDefinition } from "@/config/types";

type ClassInput = NonNullable<CentreDefinition["classes"]>[number];

/**
 * DEMO DATA — fictional weekly schedule for Gemilang Tuition Academy.
 *
 * A "class" is an offering a student can actually enrol into: a subject at a
 * level, with a tutor, on a day, at a time, in a place. Subjects are the
 * academic areas; classes are the products.
 */
export const classes: ClassInput[] = [
  {
    slug: "additional-mathematics-form-4-tuesday",
    title: "Additional Mathematics — Form 4",
    subject: "additional-mathematics",
    level: "Form 4",
    tutor: "nurul-aisyah-rahim",
    location: "kuching-central",
    day: "tue",
    startTime: "17:00",
    endTime: "18:30",
    mode: "physical",
    availability: "limited",
    trialAvailable: true,
    description:
      "The Form 4 foundation class. The first six weeks rebuild algebraic manipulation until it is genuinely fast, then the group works forward through functions, quadratics and indices with a short timed set every week.",
    highlights: [
      "Algebra diagnostic in week one",
      "Weekly timed practice marked to the scheme",
      "Maximum 12 students",
    ],
  },
  {
    slug: "additional-mathematics-form-5-thursday",
    title: "Additional Mathematics — Form 5",
    subject: "additional-mathematics",
    level: "Form 5",
    tutor: "nurul-aisyah-rahim",
    location: "kuching-central",
    day: "thu",
    startTime: "19:00",
    endTime: "21:00",
    mode: "physical",
    availability: "open",
    trialAvailable: true,
    description:
      "A two-hour SPM-year class covering differentiation, integration, vectors and statistics, with full past-year papers attempted under timed conditions from the second term onwards.",
    highlights: [
      "Full past-year papers under time",
      "Topic-by-topic mark analysis",
      "SPM answer-structure coaching",
    ],
  },
  {
    slug: "physics-form-4-wednesday",
    title: "Physics — Form 4",
    subject: "physics",
    level: "Form 4",
    tutor: "chen-wei-lun",
    location: "kuching-central",
    day: "wed",
    startTime: "17:00",
    endTime: "18:30",
    mode: "physical",
    availability: "open",
    trialAvailable: true,
    description:
      "Measurement, forces and motion, heat and light taught demonstration-first. Students finish each topic with a one-page concept summary written in their own words.",
    highlights: [
      "Demonstration-led explanations",
      "Concept summary sheets",
      "Graph interpretation drills",
    ],
  },
  {
    slug: "physics-form-5-saturday",
    title: "Physics — Form 5",
    subject: "physics",
    level: "Form 5",
    tutor: "chen-wei-lun",
    location: "kuching-central",
    day: "sat",
    startTime: "10:00",
    endTime: "12:00",
    mode: "physical",
    availability: "limited",
    trialAvailable: true,
    description:
      "Waves, electricity, electromagnetism and modern physics, plus a dedicated Paper 3 workshop every fortnight covering experiment design, tabulation and error discussion.",
    highlights: [
      "Fortnightly Paper 3 workshop",
      "Answer-language drills",
      "Full paper practice from March",
    ],
  },
  {
    slug: "physics-form-5-online-tuesday",
    title: "Physics — Form 5 (Online)",
    subject: "physics",
    level: "Form 5",
    tutor: "chen-wei-lun",
    day: "tue",
    startTime: "20:00",
    endTime: "21:30",
    mode: "online",
    availability: "open",
    trialAvailable: true,
    description:
      "A live online repeat of the Saturday Form 5 syllabus for students who cannot travel to the centre. Same tutor, same materials, recorded for revision within the same week.",
    highlights: [
      "Live, not pre-recorded",
      "Session recording for one week",
      "Digital worksheets provided",
    ],
  },
  {
    slug: "chemistry-form-4-monday",
    title: "Chemistry — Form 4",
    subject: "chemistry",
    level: "Form 4",
    tutor: "priya-devarajan",
    location: "kota-samarahan",
    day: "mon",
    startTime: "17:30",
    endTime: "19:00",
    mode: "physical",
    availability: "open",
    trialAvailable: true,
    description:
      "Atomic structure, the periodic table, bonding and the mole concept, built around visual models before any calculation is attempted.",
    highlights: [
      "Mole concept from first principles",
      "Visual bonding models",
      "Weekly calculation set",
    ],
  },
  {
    slug: "chemistry-form-5-saturday",
    title: "Chemistry — Form 5",
    subject: "chemistry",
    level: "Form 5",
    tutor: "priya-devarajan",
    location: "kuching-central",
    day: "sat",
    startTime: "14:00",
    endTime: "16:00",
    mode: "physical",
    availability: "waitlist",
    trialAvailable: false,
    description:
      "Rate of reaction, redox, thermochemistry, organic chemistry and manufactured substances, with structured revision of Form 4 calculations woven through the year.",
    highlights: [
      "Form 4 calculation revision built in",
      "Organic chemistry mapping",
      "Past-year question banks",
    ],
  },
  {
    slug: "english-form-3-tuesday",
    title: "English — Form 3",
    subject: "english",
    level: "Form 3",
    tutor: "daniel-jugah",
    day: "tue",
    startTime: "19:00",
    endTime: "20:30",
    mode: "online",
    availability: "open",
    trialAvailable: true,
    description:
      "A lower-secondary class focused on writing habit and spoken confidence, preparing students for the jump in expectations at Form 4.",
    highlights: [
      "Weekly marked writing",
      "Group discussion practice",
      "Vocabulary building",
    ],
  },
  {
    slug: "english-form-4-thursday",
    title: "English — Form 4",
    subject: "english",
    level: "Form 4",
    tutor: "daniel-jugah",
    location: "kota-samarahan",
    day: "thu",
    startTime: "17:00",
    endTime: "18:30",
    mode: "physical",
    availability: "open",
    trialAvailable: true,
    description:
      "Essay frameworks for every SPM writing format, weekly marked submissions, and comprehension strategy work in small discussion groups.",
    highlights: [
      "All SPM writing formats covered",
      "One improvement target per week",
      "Everyone speaks every session",
    ],
  },
  {
    slug: "english-form-5-friday",
    title: "English — Form 5",
    subject: "english",
    level: "Form 5",
    tutor: "daniel-jugah",
    location: "kuching-central",
    day: "fri",
    startTime: "19:00",
    endTime: "20:30",
    mode: "hybrid",
    availability: "limited",
    trialAvailable: true,
    description:
      "SPM-year English with timed writing every week, full comprehension papers and dedicated preparation for the speaking assessment. Attend in the centre or join the same session online.",
    highlights: [
      "Timed writing every week",
      "Speaking assessment preparation",
      "Attend in person or online",
    ],
  },
  {
    slug: "sejarah-form-4-sunday",
    title: "Sejarah — Form 4",
    subject: "sejarah",
    level: "Form 4",
    tutor: "faridah-mohd-salleh",
    location: "kota-samarahan",
    day: "sun",
    startTime: "10:00",
    endTime: "11:30",
    mode: "physical",
    availability: "open",
    trialAvailable: true,
    description:
      "Form 4 Sejarah taught through timelines and cause-and-effect maps rather than rote memorising, with short recall tests at the start of every session.",
    highlights: [
      "Timeline and concept mapping",
      "Start-of-class recall tests",
      "Printed summary notes",
    ],
  },
  {
    slug: "sejarah-form-5-sunday",
    title: "Sejarah — Form 5",
    subject: "sejarah",
    level: "Form 5",
    tutor: "faridah-mohd-salleh",
    location: "kuching-central",
    day: "sun",
    startTime: "14:00",
    endTime: "16:00",
    mode: "physical",
    availability: "open",
    trialAvailable: true,
    description:
      "SPM-year Sejarah with a disciplined method for KBAT and essay questions, plus structured revision of the Form 4 syllabus alongside new Form 5 content.",
    highlights: [
      "KBAT answer method",
      "Essay structure practice",
      "Form 4 revision built in",
    ],
  },
];
